name: bloc_testmate
description: Package that streamlines testing for BLoCs. tiny test-oriented DI container, not boilerplate.Supports data-driven tests, helpful matchers, and async-friendly waits.
version: 1.0.0
license: MIT
repository: https://github.com/RuLEvyDev/Bloc_TestMate
homepage: https://github.com/RuLEvyDev/Bloc_TestMate
issue_tracker: https://github.com/RuLEvyDev/Bloc_TestMate/issues
keywords:
  - bloc
  - testing
  - flutter
  - di



environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"


dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0 
  test: ^1.26.3
  flutter_test:
    sdk: flutter
  
  

dev_dependencies:

  lints: ^6.0.0
  mocktail: ^1.0.4
 
  
