name: bloc_testmate
description: Package that streamlines testing for BLoCs. It wraps `bloc_test` with a tiny test-oriented DI container and a scenario API so you can focus on behavior, not boilerplate. It also supports data-driven tests, helpful matchers, and async-friendly waits.
version: 1.0.0
license: MIT
repository: https://github.com/RuLEvyDev/Bloc_TestMate
homepage: https://github.com/RuLEvyDev/Bloc_TestMate
issue_tracker: https://github.com/RuLEvyDev/Bloc_TestMate/issues



environment:
  sdk: ^3.9.1
  flutter: ">=3.0.0"


dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  test: ^1.26.3

dev_dependencies:

  lints: ^6.0.0
  mocktail: ^1.0.4
