name: bloc_testmate
description: Package that streamlines testing for BLoCs. tiny test-oriented DI container, not boilerplate.Supports data-driven tests, helpful matchers, and async-friendly waits.
version: 1.0.3
license: MIT
repository: https://github.com/RuLEvyDev/Bloc_TestMate
homepage: https://github.com/RuLEvyDev/Bloc_TestMate
issue_tracker: https://github.com/RuLEvyDev/Bloc_TestMate/issues
keywords:
  - bloc
  - testing
  - unit-testing
  - flutter
  - di



environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

executables:
  bloc_testmate:

dependencies:
  analyzer: ^7.7.1
  args: ^2.7.0
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  glob: ^2.1.3
  path: ^1.9.1
  
  test: ^1.26.2
  yaml: ^3.1.3
  
  

dev_dependencies:

  lints: ^6.0.0
  mocktail: ^1.0.4
  
  flutter_test:
    sdk: flutter
  
  


