name: bloc_testmate
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-127.0.dev

# Add regular dependencies here.
dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  collection: ^1.19.1
  meta: ^1.17.0
  test: ^1.26.3
  # path: ^1.9.0

dev_dependencies:
  fake_async: ^1.3.3
  lints: ^6.0.0
  mocktail: ^1.0.4
