name: CI/CD for Flutter Package

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  test_analyze:
      name: Test & Analyze
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Dart
          uses: dart-lang/setup-dart@v1

        - name: Cache Flutter Dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.pub-cache
              .dart_tool
            key: ${{ runner.os }}-dart-deps-${{ hashFiles('**/pubspec.yaml') }}
            restore-keys: |
              ${{ runner.os }}-dart-deps-
        - name: Install Dependencies
          run: flutter pub get

        - name: Analyze Code
          run: dart analyze

        - name: Run Tests
          run: dart test

  # publish  if false Disable
  publish:
    name: Publish to Pub.dev 
    needs: test_analyze
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate Publish
        run: dart pub publish --dry-run

      - name: Publish to Pub.dev

        run: echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json && dart pub publish -f
