name: CI/CD for Flutter Package

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  test_analyze:
      name: Test & Analyze
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
 
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable

        - name: Cache Flutter Dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.pub-cache
              .dart_tool
            key: ${{ runner.os }}-flutter-deps-${{ hashFiles('**/pubspec.yaml') }}
            restore-keys: |
              ${{ runner.os }}-dart-deps-
              ${{ runner.os }}-flutter-deps-
        - name: Install Dependencies
          run: flutter pub get

        - name: Analyze Code
          run: flutter analyze

        - name: Run Tests
          run: flutter test

  # publish  if false Disable
  publish:
    name: Publish to Pub.dev 
    needs: test_analyze
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Validate Publish
        run: dart pub publish --dry-run

      - name: Publish to Pub.dev

        run: echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json && dart pub publish -f
